<a href="https://colab.research.google.com/github/Dummyan/data_science_bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.22.4'

### Norma wektora, długość wektora w \R^2\

In [2]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1) # norma wektora

4.0

### Norma euklidesowa w \R^n\

In [4]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

### Odległość dwóch punktów na płaszczyźnie

In [5]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

### Odległość dwóch punktów w przestrzeni R^n

In [6]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### Mnożenie macierzy

In [8]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [9]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [10]:
Z.shape

(2, 1)

In [ ]:
np.dot(Y, X)

In [12]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [13]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

### Wyznacznik macierzy

In [15]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

### Ślad macierzy

In [16]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

### Macierz jednostkowa

In [17]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
np.eye(5, dtype='bool')

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

### Macierz odwrotna

In [19]:
A

array([[ 2,  4],
       [-1,  3]])

In [20]:
B = np.linalg.inv(A)

In [21]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [22]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [23]:
np.set_printoptions(precision = 4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### Macierz transponowana

In [25]:
A

array([[ 2,  4],
       [-1,  3]])

In [26]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [27]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### Rozwiązywanie układów równań

In [28]:
A = np.array([[2, 4], [1, -1]]) # macierz współczynników
A

array([[ 2,  4],
       [ 1, -1]])

In [29]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [30]:
A_inv = np.linalg.inv(A)

In [31]:
X = np.dot(A_inv, B)

In [32]:
print(X)

[[1.]
 [2.]]
