<a href="https://colab.research.google.com/github/Dummyan/data_science_bootcamp/blob/main/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Funkcje statystyczne

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


### sum()

In [3]:
price.sum() # suma wszystkich elementów tablicy

4650.1

In [4]:
price.sum(axis=0) # sumy poszczególnych kolumn

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1) # sumy poszczególnych wierszy

array([1049.7, 2049.4, 1551. ])

In [6]:
np.sum(price)

4650.1

### min()

In [7]:
np.min(price)

11.7

In [8]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

### max()

In [9]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

### median()

In [10]:
np.median(price)

12.6

### mean()

In [11]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

### std() - odchylenie standardowe

In [12]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

### var() - wariancja

In [13]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])